version: '3'
services:
  addresses-app:
    image: ezequiel/addresses-api-app
    ports:
      - "8080:8080"
    depends_on:
      - addresses-postgres-db
  addresses-postgres-db:
    image: postgres:10.4
    environment:
      - POSTGRES_DB=addresses
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres